config/routes.rb
Stanfordiot::Application.routes.draw do
  get "users/show"

  resources :projects

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  get 'about' => 'pages#about'

  root :to => 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :image


 validates :description, presence: true
 validates :user_id, presence: true
 validates_attachment :image, presence: true,
 															content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
 															size: { less_than: 5.megabytes }

 belongs_to :user
 has_attached_file :image, styles: { medium: "320x240>"}
  	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

   def about
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_filter :authenticate_user!, except: [:index]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = current_user.projects.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = current_user.projects.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@projects = @user.projects.page(params[:page]).per_page(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    Techmakers (alpha v1.3) is brought to you by <a href="https://venture-lab.org/venture13/teams/39872" target="_blank">The IoT Team</a>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             
             <%= link_to "Techmakers", root_path, class: "brand" %>
             

                <div class="nav-collapse">
                    <ul class="nav">
                        <li><%= link_to "Home", root_path %></li>
                        <li><%= link_to "About", about_path %></li>
                    </ul>
                        <ul class="nav pull-right">
                        <% if user_signed_in? %>
                        <li><%= link_to "Add +", new_project_path %></li>
                        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                      <% else %>
                    <li><%= link_to "Login", new_user_session_path %></li>
                      <% end %>
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Techmakers</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
	</body>
</html>

app/views/pages/_home.html.erb
<% unless user_signed_in? %>

<div class="center hero-unit">
<h1>Welcome to Techmakers!</h1>
<p>
	You've found the home page for the Internet of Things Marketplace!  
</p>

<p>
	This site enables "Makers" to create and fund connected devices.  
</p>

<p>
	A place where companies can sell their connected devices.  
</p>

<p>

	And, where consumers can learn about and buy connected devices. 
</p>

<p>
  <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
</p>
</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	The 
  <%= link_to "IoT Marketplace Team", "https://venture-lab.org/venture13/teams/39872",:target => '_blank' %>
  has built the hub for all things related to the internet of things.  Inventors, Vendors and Consumers can find everything they need right here!  Find out more about this prototype by contacting members of the
  <%= link_to "IoT Marketplace Team", "https://venture-lab.org/venture13/teams/39872",:target => '_blank' %>
  .  This is our Stanford University Venture Lab Startup.
</p>
<br>
<p>
	<strong>
	Here are some scenarios of our typical users.
	</strong>
</p>	

<p>
	<strong>1) Maker (Inventor) - I need to crowdsource or crowdfund my connected device.  I want to reach a wider audience and be discovered.  “Techmakers” is the destination if you want to:</strong>
</p>
<p> -get feedback on a new connected device </p>
<p>-crowdsource the creation of a new connected device</p>
<p>-fund the creation of a new connected device</p>
<p>-find co-creators who can help build my device</p>

<br>

<p>
	<strong>2) Company (vendor) - We have a connected device that we want to sell and we want to reach a wider audience since “Techmakers” is the first Hub for connected devices, we are listing our products on Techmakers because we want to:</strong>
</p>

<p>-get discovered by vendors, retailers, and end users </p>
<p>-reach the connected generation</p>
<p>-want to educate the public about our connected devices</p>
<p>-find product testers worldwide for our new connected devices</p>

<br>

<p>
	<strong>3) Mass Market Consumer:  I am a member of the connected generation and I love all things connected.  “Techmakers” is the number one destination when I want to:</strong>
</p>
<p>-discover and purchase new connected devices </p>
<p>-vote and contribute to the creation of new connected devices</p>
<p>-fund the creation of new devices</p>
<p>-learn about new connected devices</p>







app/views/pages/home.html.erb
<% if user_signed_in? %>
	<h1>You're logged in!</h1>
<% else %>

<div class="center hero-unit">
<h1>Welcome to IoT Connect!</h1>
<p>
	You've found the home page for the Internet of Things Marketplace!
</p>
<p>
  <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
</p>
</div>
<% end %>

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  	<%= f.input :image, label: "Upload a project image" %>
    <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="box">
	<%= link_to (image_tag project.image(:medium)), project %>
	<p class="description">
		<%= project.description %>
	</p>
	<p>
		<strong>
			Posted by <%= link_to project.user.name, project.user %>
		</strong>
	</p>
	<% if current_user == project.user %>
			<p>
			    <%= link_to 'Edit', edit_project_path(project) %>
			    <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
			</p>
		  <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= render 'pages/home'%>

<div id="projects">
  <%= render @projects %>
</div>

<%= will_paginate @projects %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @project.image %>
			<p>
			  <%= @project.description %>
			</p>
			<p>
			  <%= @project.user.name %>
			</p>
			<% if current_user == @project.user %>
			<%= link_to 'Edit', edit_project_path(@project) %> |
			<% end %>
			<%= link_to 'Back', projects_path %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div id="projects">
  <%= render @projects %>
</div>

<%= will_paginate @projects %>